# allow gitops controller to modify cluster configs
# https://docs.openshift.com/container-platform/4.12/cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.html#gitops-inbuilt-permissions-for-cluster-config_configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-cluster-configs
rules:
  # configure the image registry
  - verbs:
      - "*"
    apiGroups:
      - imageregistry.operator.openshift.io
    resources:
      - configs
  # configure secrets
  - verbs:
      - "*"
    apiGroups:
      - ""
    resources:
      - secrets
  # configure routes
  - verbs:
      - "*"
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  # configure projects
  - verbs:
      - "*"
    apiGroups:
      - project.openshift.io
    resources:
      - projects
---
# assign that ClusterRole to the gitops ServiceAccount
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-manage-cluster-configs
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manage-cluster-configs
