---
# creates an admin account with the standard red hat demo password 🤫
# https://docs.openshift.com/container-platform/4.12/authentication/identity_providers/configuring-htpasswd-identity-provider.html
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd
  namespace: openshift-config
type: Opaque
data:
  htpasswd: YWRtaW46JDJ5JDA1JGdmd0JCN3BzVkdiSlFKU3hxNDJ4ZnVJbjljNkhvMHdhL3ZnY21FSS5jNHdibE44L1pVeU9LCg==
---
# configures htpasswd identity provider
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    # these are all default
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    release.openshift.io/create-only: 'true'
  name: cluster
spec:
  identityProviders:
    - htpasswd:
        fileData:
          name: htpasswd
      mappingMethod: claim
      name: htpasswd
      type: HTPasswd
---
# assigns the admin user the cluster-admin ClusterRole
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
