---
# creates registry storage as RWO to match LVM storageclass's capabilities. otherwise
# it defaults to RWM which fails
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-registry-storage
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: lvms-vg1
  volumeMode: Filesystem
---
# makes the registry available outside the cluster
apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  finalizers:
    - imageregistry.operator.openshift.io/finalizer
  name: cluster
spec:
  managementState: Managed
  storage:
    pvc:
      claim: image-registry-storage
  defaultRoute: true
  # everything below here is the default value
  logLevel: Normal
  rolloutStrategy: Recreate
  operatorLogLevel: Normal
  requests:
    read:
      maxWaitInQueue: 0s
    write:
      maxWaitInQueue: 0s
  observedConfig: null
  replicas: 1
