# sets managementStage=Managed and sets storage.pvc.claim
---
apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  finalizers:
    - imageregistry.operator.openshift.io/finalizer
  name: cluster
spec:
  logLevel: Normal
  rolloutStrategy: RollingUpdate
  operatorLogLevel: Normal
  requests:
    read:
      maxWaitInQueue: 0s
    write:
      maxWaitInQueue: 0s
  observedConfig: null
  managementState: Managed
  proxy: {}
  unsupportedConfigOverrides: null
  storage:
    pvc:
      claim:
  replicas: 1
