---
# creates registry storage as RWO to match LVM storageclass's capabilities. otherwise
# it defaults to RWM which fails
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-registry-storage
  namespace: openshift-image-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: lvms-vg1
  volumeMode: Filesystem
---
# adds persistent storage to the registry
apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  finalizers:
    - imageregistry.operator.openshift.io/finalizer
  name: cluster
spec:
  managementState: Managed
  storage:
    pvc:
      claim: image-registry-storage
  # everything below here is the default value
  defaultRoute: false
  logLevel: Normal
  rolloutStrategy: Recreate
  operatorLogLevel: Normal
  requests:
    read:
      maxWaitInQueue: 0s
    write:
      maxWaitInQueue: 0s
  observedConfig: null
  replicas: 1
---
# exposes the registry externally
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: registry
  namespace: openshift-image-registry
spec:
  host: registry.apps.sno.demo.local
  to:
    kind: Service
    name: image-registry
    weight: 100
  port:
    targetPort: 5000-tcp
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
