---
# create an empty project as a placeholder
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: demo
---
# add gitops user to demo project
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitops-manage-demo
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
---
# create a demo VM, so we have a place to run demos inside the cluster. this is
# especially important for those of us with an ARM chip, since the cluster is x86
# and we won't be able to use locally-built containers on the cluster
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: rhel9-demo
    vm.kubevirt.io/template: rhel9-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.24.2
  name: rhel9-demo
  namespace: demo
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: rhel9-demo
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  running: false
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: rhel9-demo
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - macAddress: '02:4b:48:00:00:00'
              masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel8.6.0
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: rhel9-demo
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: shadowman
              chpasswd: { expire: False }
          name: cloudinitdisk
---
# expose the VM's cockpit port so that we can make an external route next
kind: Service
apiVersion: v1
metadata:
  name: rhel9-demo
  namespace: demo
spec:
  type: ClusterIP
  selector:
    vm.kubevirt.io/name: rhel9-demo
  ports:
    - name: cockpit
      protocol: TCP
      port: 9090
      targetPort: 9090
---
# make cockpit externally accessible
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: rhel9-demo-cockpit
  namespace: demo
spec:
  host: rhel9-demo-cockpit.apps.sno.demo.local
  to:
    kind: Service
    name: rhel9-demo
    weight: 100
  port:
    targetPort: 9090
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
